name: new_super_jumper
description: Game similar to Doodle jump made with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.8.0
  flame_forge2d: ^0.14.0
  shared_preferences: ^2.1.2
  sensors_plus: ^3.0.2
  flame_texturepacker:
    git:
      url: https://github.com/Brixto/flame_texturepacker
      ref: f77ce1180fd58ba66b1a34b8a6b65d8de02d423f

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/ui/

  fonts:
    - family: DaveysDoodleface
      fonts:
        - asset: assets/fonts/DaveysDoodleface.ttf